name: bottom_bar_example
description: Demo for how to use the plugin.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  wave_bottom_bar:
    path: ../
  flutter_colorpicker: ^1.0.3

flutter:

  uses-material-design: true
