name: wave_bottom_bar
description: Flutter plugin for bottom navigation bar.
version: 1.0.0
homepage: https://github.com/wenchaosong/FlutterBottomBar

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
